---

- name: Create user
  hosts: all
  gather_facts: no
  become: yes
  roles:
    - user
  tags: user

- name: Configure OS
  hosts: all
  gather_facts: no
  become: yes
  roles:
    - os
  tags: os

- name: Setup Java
  hosts: java
  gather_facts: no
  become: yes
  roles:
    - java
  tags: java

- name: Setup Docker
  hosts: all
  gather_facts: no
  become: yes
  roles:
    - docker
  tags: docker

- name: Setup Docker on Ubuntu
  hosts: all
  gather_facts: no
  become: yes
  roles:
    - docker_ubuntu
  tags: docker_ubuntu

- name: Setup Oracle
  hosts: oracle
  gather_facts: no
  become: yes
  roles:
    - oracle
  tags: oracle

- name: Setup NiFi Single Instance
  hosts: nifi
  gather_facts: no
  become: yes
  roles:
    - nifi_single
  tags: nifi_single

- name: Setup Zookeeper
  hosts: zookeeper
  gather_facts: no
  become: yes
  roles:
    - zookeeper
  tags: zookeeper

- name: Setup Kafka
  hosts: kafka
  gather_facts: no
  become: yes
  roles:
    - kafka
  tags: kafka

- name: Setup NiFi
  hosts: nifi
  gather_facts: no
  become: yes
  roles:
    - nifi
  tags: nifi

- name: Setup Project Harbor
  hosts: harbor
  gather_facts: yes
  become: yes
  roles:
    - harbor
  tags: harbor

- name: Setup Raspberry Pi
  hosts: raspberrypi
  gather_facts: yes
  become: yes
  roles:
    - raspberrypi
  tags: raspberrypi

- name: Setup Raspberry Pi Zero
  hosts: raspberrypizero
  gather_facts: yes
  become: yes
  roles:
    - raspberrypizero
  tags: raspberrypizero

- name: Setup Raspberry Pi Servers
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - rpi_server
  tags: rpi_server
