---

docker_compose_version: 1.25.0

docker:
  compose:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
  repo:
    url: https://download.docker.com/linux/centos/docker-ce.repo

local_persist:
  url: https://github.com/CWSpear/local-persist/releases/download/v1.3.0/local-persist-linux-amd64
