all:
  hosts:
    node01:
      ansible_host: 192.168.1.111
      ansible_user: ansible
      ansible_ssh_private_key_file: ./ssh_keys/id_rsa
    node02:
      ansible_host: 192.168.1.112
      ansible_user: ansible
      ansible_ssh_private_key_file: ./ssh_keys/id_rsa
    node03:
      ansible_host: 192.168.1.113
      ansible_user: ansible
      ansible_ssh_private_key_file: ./ssh_keys/id_rsa

  children:
    java:
      hosts:
        node01:
        node02:
        node03:

    zookeeper:
      hosts:
        node01:
        node02:
        node03:

    oracle:
      hosts:
        node01:

    harbor:
      hosts:
        node01:
