all:
  hosts:
    node01:
      ansible_host: 172.16.170.240
      ansible_user: ansible
      ansible_ssh_private_key_file: ./ssh_keys/id_rsa

  children:
    oracle:
      hosts:
        node01:

    harbor:
      hosts:
        node01:
