---

- name: Enable EPEL Repo
  yum:
    name: epel-release
    update_cache: true
    state: present

- name: Install Packages
  yum:
    name: libselinux-python, curl, tar, bzip2, zip, ntp, wget, tmux, mosh , net-tools, fio, mtr, htop, glances, ntp
    update_cache: yes
    state: installed

#- name: Open mosh port
#  firewalld:
#    port: 60000-61000/udp
#    permanent: true
#    state: enabled
#  notify:
#    - Bounce firewalld
