---

- name: Evaluate oracle database instance
  stat:
    path: "{{ oracle_database_oracle_home }}/dbs/spfile{{ oracle_database_sid }}.ora"
  register: orafile

- include: create-instance-11g.yml
  when: not orafile.stat.exists and oracle_database_version == '11g'
