---

- name: Set netca response file
  template:
    src: netca-11g.rsp.j2
    dest: /tmp/netca.rsp

- name: Configure listener
  shell: "{{ oracle_database_oracle_home }}/bin/netca /silent /responseFile /tmp/netca.rsp"
  args:
    creates: "{{ oracle_database_oracle_home }}/network/admin/{{ oracle_database_listener_name }}.ora"
  become: yes
  become_user: oracle

- name: Open Oracle port
  firewalld:
    zone: public
    port: 1521/tcp
    permanent: true
    state: enabled
  notify:
    - Bounce firewalld
