---

- name: Validate Oracle database is installed
  stat:
    path: "{{ oracle_database_oracle_home }}/bin/sqlplus"
  register: sqlplus

#- debug:
#    msg: "Oracle database is already installed in this {{ oracle_database_oracle_home }}"
#  when: sqlplus.stat.exists

- include: install-db-11g.yml
  when: not sqlplus.stat.exists and oracle_database_version == '11g'
