---

- name: Set swap_file variable
  set_fact:
    swap_file: /swap1.swap

- name: Check if swap file exists
  stat:
    path: "{{ swap_file }}"
  register: swap_file_check

- name: Create 1GB swap space
  command: "dd if=/dev/zero of={{ swap_file }} bs=1024 count=1048576"
  when: not swap_file_check.stat.exists

- name: Set permissions on swap file
  file:
    path: "{{ swap_file }}"
    mode: 0600
  when: not swap_file_check.stat.exists

- name: Format swap file
  command: "mkswap {{ swap_file }}"
  when: not swap_file_check.stat.exists

- name: Turn on swap
  command: "swapon {{ swap_file }}"
  when: not swap_file_check.stat.exists

- name: Set swapiness
  sysctl:
    name: vm.swappiness
    value: "1"
  when: not swap_file_check.stat.exists

- name: Add to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: "{{ swap_file }}"
    line: "{{ swap_file }} none swap sw 0 0"
  when: not swap_file_check.stat.exists
