---

- name: Upgrade packages
  apt:
    upgrade: dist
  tags: upgrade

- name: Install nexmon required packages
  apt:
    name:
      - raspberrypi-kernel-headers
      - git
      - libgmp3-dev
      - gawk
      - qpdf
      - bison
      - flex
      - make
    state: present
    update_cache: yes
  tags: packages
#
#Clone   git clone https://github.com/seemoo-lab/nexmon.git
#
#Go into the root directory of our repository: cd nexmon
#
#Check if /usr/lib/arm-linux-gnueabihf/libisl.so.10 exists
#- if not, compile it from source:
#    cd buildtools/isl-0.10
#    ./configure
#    make
#    make install
#    ln -s /usr/local/lib/libisl.so /usr/lib/arm-linux-gnueabihf/libisl.so.10
#
#Check if /usr/lib/arm-linux-gnueabihf/libmpfr.so.4 exists
#- if not, compile it from source:
#    cd buildtools/mpfr-3.1.4
#    autoreconf -f -i
#    ./configure
#    make
#    make install
#    ln -s /usr/local/lib/libmpfr.so /usr/lib/arm-linux-gnueabihf/libmpfr.so.4
#
#Then you can setup the build environment for compiling firmware patches
#- Setup the build environment: source setup_env.sh
#- Compile some build tools and extract the ucode and flashpatches from the original firmware files: make
#
#Go to the patches folder for the bcm43430a1/bcm43455c0 chipset:
#- cd patches/bcm43430a1/7_45_41_46/nexmon/
#- Compile a patched firmware: make
#- Generate a backup of your original firmware file: make backup-firmware
#- Install the patched firmware on your RPI3: make install-firmware
#
#Install nexutil: from the root directory of our repository switch to the nexutil folder:
#- cd utilities/nexutil/
#- Compile and install nexutil: make && make install
#
#Optional: remove wpa_supplicant for better control over the WiFi interface: apt-get remove wpasupplicant
#
#Note: To connect to regular access points you have to execute nexutil -m0 first
#
