---
- name: Reload systemctl daemon
  command: systemctl daemon-reload

- name: Bounce firewalld
  service:
    name: firewalld
    state: restarted

- name: Restart zookeeper service
  service:
    name: zookeeper
    state: restarted
