---
galaxy_info:
  author: jeqo (quilcate.jorge@gmail.com)
  description: oracle database role to install database software and create and configure instances and listeners.

  license: MIT

  min_ansible_version: 2.0

  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
  - oracle
  - database
  - database:sql
dependencies: []
