---

- name: Copying NiFi Service template
  template:
    src: nifi.service.j2
    dest: /etc/systemd/system/nifi.service
    mode: 0750
  become: true

- name: Re/Starting NiFi Service systemd
  service:
    name: nifi.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: true
