---

- name: Create installer directory
  file:
    path: "{{ installer.path }}"
    state: directory

- name: Download Harbor
  get_url:
    url: "{{ harbor.binary.url }}"
    dest: "{{ installer.path }}"
  when: download_harbor|bool

- name: Copy Harbor installer
  copy:
    src: harbor-offline-installer-v1.8.1.tgz
    dest: "{{ installer.path }}/harbor-offline-installer-v1.8.1.tgz"
  when: not download_harbor|bool

- name: Uncompress Harbor
  unarchive:
    src: "{{ installer.path }}/{{ harbor.binary.file }}"
    dest: "{{ harbor.install.path }}"
    remote_src: yes

- name: Configuration harbor
  template:
    src: harbor.cfg.j2
    dest: "{{ harbor.install.path }}/harbor/harbor.cfg"

- name: Setup harbor
  shell: "{{ harbor.install.path }}/harbor/install.sh"
  args:
    chdir: "{{ harbor.install.path }}/harbor/"

- name: Open port
  firewalld:
    service: http
    permanent: yes
    state: enabled
  notify:
    - Bounce firewalld
